version: '3.8'

services:
  app:
    build: .
    working_dir: /app
    command: flask run --host 0.0.0.0
    expose:
      - "5000:5000"
    ports:
      - "8000:5000"

  mysql:
    image: mysql
    container_name: db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123"
    command: --init-file /app/init.sql
    volumes:
        - ./init.sql:/app/init.sql
    