version: '3.8'

services:
  app:
    build: .
    working_dir: /app
    command: flask run --host 0.0.0.0
    expose:
      - "5000:5000"

  mysql:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123